const drinks=[{name:'Cà phê sữa đá',description:'Đậm vị cà phê, ngọt dịu sữa đặc, thêm đá cho một ngày Hà Nội.',type:'coffee'},{name:'Bạc xỉu',description:'Nhiều sữa hơn, nhẹ vị cà phê. Hợp khi bạn muốn chút ngọt ngào.',type:'coffee'},{name:'Americano đá',description:'Một lựa chọn đơn giản, không sữa, không quá cầu kỳ.',type:'coffee'},{name:'Latte',description:'Cà phê espresso cùng sữa, êm và dễ uống.',type:'coffee'},{name:'Cappuccino',description:'Espresso, sữa nóng và lớp bọt sữa mịn.',type:'coffee'},{name:'Cà phê đen đá',description:'Gọn gàng, đậm đà. Thêm đường theo khẩu vị của bạn.',type:'coffee'},{name:'Matcha latte',description:'Vị trà xanh cùng sữa. Một chút đổi vị cho buổi đi cà phê.',type:'other'},{name:'Trà đào',description:'Một món trà trái cây tươi mát, dễ nhâm nhi.',type:'other'},{name:'Chocolate',description:'Vị cacao và sữa cho một buổi nghỉ ngọt ngào.',type:'other'},{name:'Trà chanh',description:'Chua nhẹ, thanh mát. Hỏi quán mức đường bạn thích.',type:'other'}];
let cafes=[],currentCafe='',currentDrink=null,busy=false;const el=id=>document.getElementById(id);
function choose(items,previous){const pool=items.filter(item=>item!==previous);return pool[Math.floor(Math.random()*pool.length)]||items[0]}
function pickDrink(){const type=el('drinkType').value;currentDrink=choose(drinks.filter(d=>type==='all'||d.type===type),currentDrink);el('drinkName').textContent=currentDrink.name;el('drinkDescription').textContent=currentDrink.description}
function renderCafe(){el('cafe').textContent=currentCafe;el('number').textContent='HÀ NỘI / '+String(cafes.indexOf(currentCafe)+1).padStart(3,'0');el('maps').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(currentCafe+' Hà Nội');pickDrink()}
function setTheme(theme){document.documentElement.dataset.theme=theme;el('themeToggle').textContent=theme==='dark'?'☀ Sáng':'☾ Tối';el('themeToggle').setAttribute('aria-pressed',String(theme==='dark'));el('themeToggle').setAttribute('aria-label',theme==='dark'?'Bật giao diện sáng':'Bật giao diện tối');try{localStorage.setItem('coffee-theme',theme)}catch{}}
let initialTheme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';try{const saved=localStorage.getItem('coffee-theme');if(['light','dark'].includes(saved))initialTheme=saved}catch{}setTheme(initialTheme);el('themeToggle').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
let reelAnimation=null;
function makeReel(winner,index){const track=el('reelTrack');track.replaceChildren();for(let i=0;i<index+4;i++){const card=document.createElement('div');card.className='reel-card';const tag=document.createElement('span');tag.textContent='HÀ NỘI / '+String(i+1).padStart(2,'0');const name=document.createElement('strong');name.textContent=i===index?winner:choose(cafes);card.append(tag,name);track.append(card)}return track}
function reelOffset(index){const card=el('reelTrack').children[0];const width=card?.getBoundingClientRect?.().width||220;const gap=typeof getComputedStyle==='function'?parseFloat(getComputedStyle(el('reelTrack')).gap)||12:12;return el('reelWindow').clientWidth/2-index*(width+gap)-width/2}
function restReel(){if(!currentCafe||busy)return;if(reelAnimation)reelAnimation.cancel();const track=makeReel(currentCafe,2);track.style.transform=`translateX(${reelOffset(2)}px)`;track.children[2].classList.add('winner')}
async function spinReel(winner){const index=30,track=makeReel(winner,index);if(reelAnimation)reelAnimation.cancel();const start=reelOffset(2),end=reelOffset(index);track.style.transform=`translateX(${end}px)`;if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&track.animate){reelAnimation=track.animate([{transform:`translateX(${start}px)`},{transform:`translateX(${end}px)`}],{duration:3800,easing:'cubic-bezier(.12,.72,.12,1)',fill:'none'});await reelAnimation.finished.catch(()=>{})}track.style.transform=`translateX(${reelOffset(index)}px)`;track.children[index].classList.add('winner')}
window.addEventListener('resize',restReel);
async function shuffle(){if(busy||!cafes.length)return;busy=true;el('shuffle').disabled=true;el('reroll').disabled=true;el('drinkType').disabled=true;el('maps').hidden=true;el('spinStatus').textContent='Đang quay…';document.body.classList.add('rolling');try{const winner=choose(cafes,currentCafe);await spinReel(winner);currentCafe=winner;renderCafe();el('spinStatus').textContent='Đã chọn: '+currentCafe;return {cafe:currentCafe,drink:currentDrink.name,menuVerified:false}}finally{busy=false;el('shuffle').disabled=false;el('reroll').disabled=false;el('drinkType').disabled=false;el('maps').hidden=false;document.body.classList.remove('rolling')}}
el('shuffle').addEventListener('click',shuffle);el('reroll').addEventListener('click',pickDrink);el('drinkType').addEventListener('change',()=>{if(currentDrink)pickDrink()});
fetch('cafes.json').then(r=>{if(!r.ok)throw Error('List unavailable');return r.json()}).then(data=>{cafes=data.places.filter(n=>n!=='Sky City Tower');if(!cafes.length)throw Error('Empty list');currentCafe=choose(cafes);renderCafe();restReel();if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'pick_cafe_and_drink',description:'Choose a random Hanoi cafe and a general drink suggestion, updating the visible result. Drinks are not verified menu items.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');if(busy)throw Error('A selection is in progress');return await shuffle()}})).catch(()=>{})}catch{}}}).catch(()=>{el('error').hidden=false;el('cafe').textContent='Chưa tải được danh sách';el('shuffle').disabled=true;el('reroll').disabled=true;el('maps').hidden=true});

